### ISSUE TITLE
London sectors showing as banbox

### ISSUE THREAD

**Issue by Connorseds2002** [vatsimnetwork/vatspy-data-project#78] opened 2020-06-27 13:06 UTC
The London sectors on vatspy are showing link there are controlling on the bandbox it would help pilots on the ground that there could be using the correct part of the UK so that controller does not have to send then a message with a link to the vatsim UK sectors image

**Comment by nepetadosmil** [comment] 2020-06-27 15:15
Duplicate of #25

**Closed by nepetadosmil** 2020-06-27 15:15 UTC
