### ISSUE TITLE
LBSR and LBWR sectors merge

### ISSUE THREAD

**Issue by dsolesvik** [vatsimnetwork/vatspy-data-project#274] opened 2021-02-28 19:24 UTC
LBWR_CTR is not in use anymore and the Varna sector, covered by LBWR is now covered by LBSR_V_CTR. LBSR_CTR is the main Sofia FIR position which covers both FIRs. I would like to request for the LBSR and LBWR sectors to be merged into one whole LBSR Bulgarian sector, as for some pilots it apparently shows that LBSR_CTR, the bandbox position, doesn't cover the Eastern Varna sector. Thank you!

**Comment by Adrian2k** [comment] 2021-03-03 14:11
I can remove LBWR if an authorized staff member of Bulgaria (see info on project page or readme file) can confirm LBWR is not used.

**Comment by kusterjs** [comment] 2021-03-07 21:02
Not a staff member, but involved in creating the sector file since a few years. I can confirm @dsolesvik report.
#280 created

**Comment by Adrian2k** [comment] 2021-03-07 23:42
Fixed in #280

**Closed by Adrian2k** 2021-03-07 23:42 UTC
Labels: removal
